module.exports = function LoadCachedDataMW() {
    return (req, res, next) => {
        const recipesData = {
            recipes: [
                {
                    is_one_top: false,
                    cook_time_minutes: 10,
                    promotion: "full",
                    keywords: "",
                    show: {
                        servings_noun_plural: "servings",
                        canonical_id: "recipe:8110",
                        show_id: 63,
                        draft_status: "published"
                    },
                    sections: [],
                    tags: [],
                    thumbnail_alt_text: "101",
                    credits: {},
                    topics: [],
                    slug: "how-to-make-classic-french-toast",
                    servings_noun_singular: "serving",
                    video_url: "https://vid.tasty.co/output/215487/hls24_1631150838.m3u8",
                    prep_time_minutes: 5,
                    name: "How To Make Classic French Toast",
                    buzz_id: null,
                    thumbnail_url: "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/341495.jpg",
                    is_shoppable: true,
                    video_id: 135115,
                    compilations: [],
                    num_servings: 4,
                    brand: null,
                    nutrition: {},
                    tips_and_ratings_enabled: true,
                    video_ad_content: "none",
                    seo_title: "",
                    country: "US",
                    instructions: [],
                    language: "eng",
                    brand_id: null,
                    aspect_ratio: "16:9",
                    description: "This iconic dish is all about the details. While french toast might seem simple, looks can be deceiving. To get that perfectly crispy exterior and creamy, silky custard on the inside we spent weeks eating tons of butter, bread, and syrup to discover the best classic french toast recipe. The end result is indulgent, delicious, and most importantly, easy to make. What’s not to love?",
                    inspired_by_url: null,
                    total_time_minutes: 20,
                    nutrition_visibility: "auto",
                    facebook_posts: [],
                    total_time_tier: "",
                    yields: "Servings: 4",
                    original_video_url: "https://s3.amazonaws.com/video-api-prod/assets/42109c902ae449bda59cebafa04745ca/BFV81893_FrenchToast_ADB_090821_Final_16x9_YT.mp4",
                    updated_at: 1645125797,
                    renditions: [],
                    created_at: 1644534455,
                    approved_at: 1645125797,
                    user_ratings: [],
                    id: 8110
                },
                {
                    is_one_top: false,
                    cook_time_minutes: null,
                    promotion: "full",
                    keywords: "",
                    show: {
                        description: "",
                        is_one_top: false,
                        beauty_url: null,
                        seo_title: "",
                        facebook_posts: [],
                        keywords: "",
                        compilations: [],
                        buzz_id: null,
                        thumbnail_url: "https://img.buzzfeed.com/tasty-app-user-assets-prod-us-east-1/recipes/11e6176999dd4d3fa7444224e8891cdb.jpeg",
                        credits: {},
                        total_time_tier: "",
                        cook_time_minutes: null,
                        nutrition_visibility: "auto",
                        language: "eng",
                        id: 8107,
                        show_id: 17,
                        num_servings: 4,
                        thumbnail_alt_text: "",
                        video_url: null,
                        country: "US",
                        sections: [],
                        brand_id: null,
                        name: "Easy Beef Hand Pies",
                        updated_at: 1645125674,
                        is_shoppable: true,
                        yields: "Servings: 4",
                        instructions: [],
                        inspired_by_url: null,
                        renditions: [],
                        canonical_id: "recipe:8107",
                        draft_status: "published",
                        tips_and_ratings_enabled: true,
                        created_at: 1644532621
                    },
                    sections: [],
                    tags: [],
                    slug: "easy-beef-hand-pies",
                    servings_noun_singular: "serving",
                    video_url: null,
                    prep_time_minutes: null,
                    name: "Easy Beef Hand Pies",
                    buzz_id: null,
                    thumbnail_url: "https://img.buzzfeed.com/tasty-app-user-assets-prod-us-east-1/recipes/11e6176999dd4d3fa7444224e8891cdb.jpeg",
                    is_shoppable: true,
                    video_id: null,
                    compilations: [],
                    num_servings: 4,
                    brand: null,
                    nutrition: {},
                    tips_and_ratings_enabled: true,
                    video_ad_content: null,
                    seo_title: "",
                    country: "US",
                    instructions: [],
                    language: "eng",
                    brand_id: null,
                    aspect_ratio: "16:9",
                    description: "",
                    inspired_by_url: null,
                    total_time_minutes: null,
                    nutrition_visibility: "auto",
                    facebook_posts: [],
                    total_time_tier: "",
                    yields: "Servings: 4",
                    original_video_url: null,
                    updated_at: 1645125674,
                    renditions: [],
                    created_at: 1644532621,
                    approved_at: 1645125673,
                    user_ratings: [],
                    id: 8107
                },
                {
                    is_one_top: false,
                    cook_time_minutes: null,
                    promotion: "full",
                    keywords: "",
                    show: {
                        description: "",
                        is_one_top: false,
                        beauty_url: "https://img.buzzfeed.com/video-api-prod/assets/095902ca46a847d1a75e5f16bcdf06c6/InstantRamen_Pinterest.jpg",
                        seo_title: "",
                        facebook_posts: [],
                        keywords: "",
                        compilations: [],
                        buzz_id: null,
                        thumbnail_url: "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/366047.jpg",
                        credits: {},
                        total_time_tier: "",
                        cook_time_minutes: null,
                        nutrition_visibility: "auto",
                        language: "eng",
                        id: 8106,
                        show_id: 25,
                        num_servings: 1,
                        thumbnail_alt_text: "",
                        video_url: null,
                        country: "US",
                        sections: [],
                        brand_id: null,
                        name: "I Made The Iconic Tasty Instant Ramen",
                        updated_at: 1645125591,
                        is_shoppable: true,
                        yields: "Servings: 1",
                        instructions: [],
                        inspired_by_url: null,
                        renditions: [],
                        canonical_id: "recipe:8106",
                        draft_status: "published",
                        tips_and_ratings_enabled: true,
                        created_at: 1644532075
                    },
                    sections: [],
                    tags: [],
                    slug: "i-made-the-iconic-tasty-instant-ramen",
                    servings_noun_singular: "serving",
                    video_url: null,
                    prep_time_minutes: null,
                    name: "I Made The Iconic Tasty Instant Ramen",
                    buzz_id: null,
                    thumbnail_url: "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/366047.jpg",
                    is_shoppable: true,
                    video_id: null,
                    compilations: [],
                    num_servings: 1,
                    brand: null,
                    nutrition: {},
                    tips_and_ratings_enabled: true,
                    video_ad_content: null,
                    seo_title: "",
                    country: "US",
                    instructions: [],
                    language: "eng",
                    brand_id: null,
                    aspect_ratio: "16:9",
                    description: "",
                    inspired_by_url: null,
                    total_time_minutes: null,
                    nutrition_visibility: "auto",
                    facebook_posts: [],
                    total_time_tier: "",
                    yields: "Servings: 1",
                    original_video_url: null,
                    updated_at: 1645125591,
                    renditions: [],
                    created_at: 1644532075,
                    approved_at: 1645125591,
                    user_ratings: [],
                    id: 8106
                }
            ]
        };
        res.locals.recipeData = recipesData.recipes;
        return next();
    };
}